export { default as MasterContent } from "./Component/MasterContent.master"
export { default as MasterTittleBlock } from "./Component/TittleMasterBlock"
export { default as MasterPortretBlock } from "./Component/PortretMasterBlock"
export { default as TittleBlock } from "./Component/TittleBlock"
export { default as ContentBlock } from "./Component/ContentBlock"
export { default as ButtonBlock } from "./Component/ButtonBLock"
